@baseUrl = http://localhost:3000

### Pesquisa todos os books
GET {{baseUrl}}/api/books

### Cria um novo book
POST {{baseUrl}}/api/books
Content-Type: application/json

{
  "title": "Clean Code",
  "description": "Livro para programadores sobre código limpo.",
  "pageCount": 520,
  "publishDate": "2010-01-01"
}


### Pesquisa book específico
GET {{baseUrl}}/api/books/674e53f2968dc4a7c071c971

### Altera o book com id=1
PUT {{baseUrl}}/api/books/674e53a710b7c1ccba8fe5f1
Content-Type: application/json

{
  "title": "Teste new title"
}

### Exclui um book 
DELETE {{baseUrl}}/api/books/674e527d704e130c154b4fc8
